STATUS_STRATEGY_ACTIVE = 1
STATUS_STRATEGY_INACTIVE = 2

C_STATUS_STRATEGY = (
    (STATUS_STRATEGY_ACTIVE, 'Active'),
    (STATUS_STRATEGY_INACTIVE, 'Inactive')
)


STATUS_STRATEGY_QUADRANT_ACTIVE = 1
STATUS_STRATEGY_QUADRANT_INACTIVE = 2

C_STATUS_STRATEGY_QUADRANT = (
    (STATUS_STRATEGY_QUADRANT_ACTIVE, 'Active'),
    (STATUS_STRATEGY_QUADRANT_INACTIVE, 'Inactive')
)


STATUS_STRATEGY_CANDLE_ACTIVE = 1
STATUS_STRATEGY_CANDLE_INACTIVE = 2


C_STATUS_STRATEGY_CANDLE = (
    (STATUS_STRATEGY_CANDLE_ACTIVE, 'Active'),
    (STATUS_STRATEGY_CANDLE_INACTIVE, 'Inactive')
)


COLOR_STRATEGY_CANDLE_GREEN = 1
COLOR_STRATEGY_CANDLE_RED = 2

C_COLOR_STRATEGY_CANDLE = (
    (COLOR_STRATEGY_CANDLE_GREEN, 'Green'),
    (COLOR_STRATEGY_CANDLE_RED, 'Red')
)


STATUS_STRATEGY_TIME_ACTIVE = 1
STATUS_STRATEGY_TIME_INACTIVE = 2

C_STATUS_STRATEGY_TIME = (
    (STATUS_STRATEGY_TIME_ACTIVE, 'Active'),
    (STATUS_STRATEGY_TIME_INACTIVE, 'Inactive')
)


TYPE_STRATEGY_TIME_CHECKING = 1
TYPE_STRATEGY_TIME_STARTING = 2

C_TYPE_STRATEGY_TIME = (
    (TYPE_STRATEGY_TIME_CHECKING, 'Checking'),
    (TYPE_STRATEGY_TIME_STARTING, 'Starting'),
)