# Generated by Django 2.2.12 on 2024-01-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('active', '0001_initial'),
        ('account', '0001_initial'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='account.AccountModel')),
                ('active', models.ManyToManyField(related_name='managements', to='active.ActiveModel')),
                ('cycles', models.ManyToManyField(blank=True, related_name='managements', to='cycle.CycleModel')),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Management',
                'db_table': 'management',
            },
        ),
        migrations.CreateModel(
            name='ManagementByStrategyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('use_candle_color_filter', models.BooleanField(default=False)),
                ('initial_candle_color_filter', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_candle_color_filter', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('use_candle_color_filter_result', models.BooleanField(default=False)),
                ('initial_candle_color_filter_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_candle_color_filter_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('use_candle_similarity_filter', models.BooleanField(default=False)),
                ('levels_candle_similarity_filter', models.IntegerField(default=0)),
                ('initial_candle_similarity_filter', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_candle_similarity_filter', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('use_candle_similarity_filter_result', models.BooleanField(default=False)),
                ('levels_candle_similarity_filter_result', models.IntegerField(default=0)),
                ('initial_candle_similarity_filter_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_candle_similarity_filter_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('use_trader_mood', models.BooleanField(default=False)),
                ('initial_trader_mood', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_trader_mood', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements_by_strategies', to='management.ManagementModel')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements_by_strategies', to='strategy.StrategyModel')),
            ],
            options={
                'verbose_name': 'Management By Strategy',
                'verbose_name_plural': 'Managements By Strategies',
                'db_table': 'management_by_strategy',
            },
        ),
    ]
