STATUS_ACCOUNT_ACTIVE = 1
STATUS_ACCOUNT_INACTIVE = 2


C_STATUS_ACCOUNT = (
    (STATUS_ACCOUNT_ACTIVE, 'Active'),
    (STATUS_ACCOUNT_INACTIVE, 'Inactive')
)


GENDER_ACCOUNT_MALE = 1
GENDER_ACCOUNT_FEMALE = 2

C_GENDER_ACCOUNT = (
    (GENDER_ACCOUNT_MALE, 'Male'),
    (GENDER_ACCOUNT_FEMALE, 'Female')
)
