# Generated by Django 2.2.12 on 2024-01-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyclemodel',
            old_name='soros',
            new_name='serums',
        ),
        migrations.RenameField(
            model_name='cyclemodel',
            old_name='soros_percentage_profit',
            new_name='serums_percentage_profit',
        ),
    ]
