# Generated by Django 2.2.12 on 2024-01-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='account.AccountModel')),
                ('cycles', models.ManyToManyField(blank=True, related_name='strategies', to='cycle.CycleModel')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategy',
            },
        ),
        migrations.CreateModel(
            name='StrategyQuadrantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies_quadrants', to='strategy.StrategyModel')),
            ],
            options={
                'verbose_name': 'Strategy Quadrant',
                'verbose_name_plural': 'Strategies Quadrants',
                'db_table': 'strategy_quadrant',
            },
        ),
        migrations.CreateModel(
            name='StrategyTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(1, 'Checking'), (2, 'Starting')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('strategy_quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies_times', to='strategy.StrategyQuadrantModel')),
            ],
            options={
                'verbose_name': 'Strategy Time',
                'verbose_name_plural': 'Strategies Times',
                'db_table': 'strategy_time',
            },
        ),
        migrations.CreateModel(
            name='StrategyCandleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(default=0)),
                ('color', models.IntegerField(choices=[(1, 'Green'), (2, 'Red')])),
                ('compare', models.BooleanField(default=False)),
                ('conditional', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies_candles', to='strategy.StrategyModel')),
            ],
            options={
                'verbose_name': 'Strategy Candle',
                'verbose_name_plural': 'Strategies Candles',
                'db_table': 'strategy_candle',
            },
        ),
    ]
